export { PopoverMode, PopoverPlacement } from 'react-native-popover-view'
export { theme, lightColors, darkColors, palettes, fontStyles, } from './utiles/theme'
export { styled } from './utiles/styled'
export { Stack, type StackProps } from './stack'
export { StyledText, type StyledTextProps } from './text'
export { StyledSafeAreaProvider, type StyledSafeAreaProviderProps } from './safeAreaProvider'
export { StyledSafeAreaView, type StyledSafeAreaViewProps } from './safeAreaView'
export { StyledScrollView, type StyledScrollViewProps } from './scrollView'
export { StyleShape, type ShapeProps } from './shape'
export { StyledPage, type StyledPageProps } from './page'
export { StyledHeader, type HeaderProps } from './header'
export { StyledSpacer, type SpacerProps } from './spacer'
